# ENV
export PNPM_HOME="$HOME/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
export DOTNET_ROOT=$HOME/.dotnet
export ZSH="$HOME/.oh-my-zsh"
export PATH=$PATH:/usr/local/go/bin
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$PATH:$HOME/go/bin"
export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools
export EDITOR='nvim'
export GTK_THEME='Adwaita:dark'
export XCURSOR_THEME="Bibata-Modern-Classic"
export XCURSOR_SIZE=24
export STARSHIP_CONFIG=~/.config/starship/starship.toml
export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket
