#! /bin/sh
# autostart
pgrep -x sxhkd >/dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

# config
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 0
bspc config window_gap 8

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_following_pointer true
bspc config pointer_modifier super

bspc rule -a firefox desktop='^2' focus=false
bspc rule -a Chromium desktop='^2' focus=false
bspc rule -a Spotify desktop='^9' focus=false
bspc rule -a TelegramDesktop desktop='^10' focus=false
bspc rule -a Screenkey manage=off

bspc rule --add Alacritty state=floating rectangle=1300x900+0+0 center=true
