theme = "catppuccin_mocha"

[editor]
line-number = "absolute"
mouse = false
scrolloff = 5
middle-click-paste = false
shell = [ "zsh", "-c" ]
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""  # set wrap-indicator to "" to hide it

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1 
      
[keys.select]
"$" = "goto_line_end"
"U" = "switch_to_uppercase"
"u" = "switch_to_uppercase"

[keys.normal]
"$" = "goto_line_end"
C-s = ":w" # Maps Ctrl-s to the typable command :w which is an alias for :write (save file)
g = { a = "code_action" } # Maps `ga` to show possible code actions
0 = "goto_line_start"
S-k = "hover"
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"esc" = ["collapse_selection", "normal_mode"]

[keys.normal."space"]
"space" = "last_picker"

